const LOAD_USERS = 'LOAD_USERS';
const LOAD_POSTS = 'LOAD_POSTS';
const LOAD_COMMENTS = 'LOAD_COMMENTS';
const LOAD_SINGLE_USER = 'LOAD_SINGLE_USER';

export {
    LOAD_USERS,
    LOAD_POSTS,
    LOAD_COMMENTS,
    LOAD_SINGLE_USER
}